In [ ]:
import matplotlib.pyplot as plt
from matplotlib import style
style.use('ggplot')
import numpy as np
from random import randint
from math import sqrt
from sklearn.metrics import silhouette_score
from sklearn import cluster
from scipy.cluster.hierarchy import dendrogram, linkage

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving iris_org.txt to iris_org.txt


In [ ]:
read_file=open("iris_org.txt",'r')
read_content= read_file.read()

all_data= read_content.splitlines()
No_data_points=len(all_data)
print ("Number of the data points :- ", No_data_points)
features = all_data[0].split("\t")
No_of_features = len(features)-1
print ("Number the features/samples :- ", No_of_features)

Df=np.zeros((No_data_points,No_of_features))
true_label = []
counter = 0
for lines in all_data:
    values=lines.split('\t')
    for i in range(0,No_of_features):
        Df[counter][i]= values[i]
    true_label.append(int(values[No_of_features]))     #
    counter+=1
print (Df)

Number of the data points :-  150
Number the features/samples :-  4
[[5.1 3.5 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.3 3.3 6.  2.5]
 [4.9 3.  1.4 0.2]
 [6.4 3.2 4.5 1.5]
 [5.8 2.7 5.1 1.9]
 [4.7 3.2 1.3 0.2]
 [6.9 3.1 4.9 1.5]
 [7.1 3.  5.9 2.1]
 [4.6 3.1 1.5 0.2]
 [5.5 2.3 4.  1.3]
 [6.3 2.9 5.6 1.8]
 [5.  3.6 1.4 0.2]
 [6.5 2.8 4.6 1.5]
 [6.5 3.  5.8 2.2]
 [5.4 3.9 1.7 0.4]
 [5.7 2.8 4.5 1.3]
 [7.6 3.  6.6 2.1]
 [4.6 3.4 1.4 0.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.5 4.5 1.7]
 [5.  3.4 1.5 0.2]
 [4.9 2.4 3.3 1. ]
 [7.3 2.9 6.3 1.8]
 [4.4 2.9 1.4 0.2]
 [6.6 2.9 4.6 1.3]
 [6.7 2.5 5.8 1.8]
 [4.9 3.1 1.5 0.1]
 [5.2 2.7 3.9 1.4]
 [7.2 3.6 6.1 2.5]
 [5.4 3.7 1.5 0.2]
 [5.  2.  3.5 1. ]
 [6.5 3.2 5.1 2. ]
 [4.8 3.4 1.6 0.2]
 [5.9 3.  4.2 1.5]
 [6.4 2.7 5.3 1.9]
 [4.8 3.  1.4 0.1]
 [6.  2.2 4.  1. ]
 [6.8 3.  5.5 2.1]
 [4.3 3.  1.1 0.1]
 [6.1 2.9 4.7 1.4]
 [5.7 2.5 5.  2. ]
 [5.8 4.  1.2 0.2]
 [5.6 2.9 3.6 1.3]
 [5.8 2.8 5.1 2.4]
 [5.7 4.4 1.5 0.4]
 [6.7 3.1 4.4 1.4]
 [6.4 3.2 5.3 2.3]
 [5.4 3.9 1.3 0.4]
 

In [ ]:
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler

In [ ]:
D = StandardScaler().fit_transform(Df)

In [ ]:
print(D)

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [ 1.40150837e+00  3.28414053e-01  5.35408562e-01  2.64141916e-01]
 [ 5.53333275e-01  5.58610819e-01  1.27429511e+00  1.71209594e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [ 6.74501145e-01  3.28414053e-01  4.21733708e-01  3.95774101e-01]
 [-5.25060772e-02 -8.22569778e-01  7.62758269e-01  9.22302838e-01]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [ 1.28034050e+00  9.82172869e-02  6.49083415e-01  3.95774101e-01]
 [ 1.52267624e+00 -1.31979479e-01  1.21745768e+00  1.18556721e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-4.16009689e-01 -1.74335684e+00  1.37546573e-01  1.32509732e-01]
 [ 5.53333275e-01 -3.62176246e-01  1.04694540e+00  7.90670654e-01]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [ 7.95669016e-01 -5.92373012e-01  4.78571135e-01  3.95774101e-01]
 [ 7.95669016e-01 -1.31979479e-01  1.16062026e+00  1.31719939e

**K=3**

In [ ]:
from sklearn import metrics
linkage_style= "single"

for i in range(3,4):
    agglomerative = cluster.AgglomerativeClustering(n_clusters=3, linkage=linkage_style, affinity='euclidean')
    idx = agglomerative.fit_predict(D)
    hlabels = agglomerative.labels_ 
    print (hlabels) 
    score = silhouette_score(D,hlabels)
    ARI=metrics.adjusted_rand_score(true_label, hlabels)
    print ("Silhouette Score", score)
    print ("ARI Score",ARI)

[1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1
 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0
 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0
 1 0 0 1 0 0 1 0 0 1 0 0 2 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1
 0 0]
Silhouette Score 0.5046456108325449
ARI Score 0.5583714437541352


**K=4**

In [ ]:
from sklearn import metrics
linkage_style= "single"

for i in range(3,4):
    agglomerative = cluster.AgglomerativeClustering(n_clusters=4, linkage=linkage_style, affinity='euclidean')
    idx = agglomerative.fit_predict(D)
    hlabels = agglomerative.labels_ 
    print (hlabels) 
    score = silhouette_score(D,hlabels)
    ARI=metrics.adjusted_rand_score(true_label, hlabels)
    print ("Silhouette Score", score)
    print ("ARI Score",ARI)

[3 1 1 3 1 1 3 1 1 3 1 1 3 1 1 3 1 1 3 1 1 3 1 1 3 1 1 3 1 0 3 1 1 3 1 1 3
 1 1 3 1 1 3 1 1 3 1 1 3 1 1 3 1 0 3 1 1 3 1 1 3 1 1 3 1 1 3 1 1 3 1 1 3 1
 1 3 1 1 3 1 1 3 1 1 3 1 1 3 1 1 3 1 1 3 1 0 3 1 1 3 1 1 3 1 1 3 1 1 3 1 1
 3 1 1 3 1 1 3 1 1 3 1 1 2 1 1 3 1 1 3 1 1 3 1 1 3 1 1 3 1 1 3 1 1 3 1 1 3
 1 1]
Silhouette Score 0.4067464623524494
ARI Score 0.5522031331345545


**K=5**

In [ ]:
from sklearn import metrics
linkage_style= "single"

for i in range(3,4):
    agglomerative = cluster.AgglomerativeClustering(n_clusters=5, linkage=linkage_style, affinity='euclidean')
    idx = agglomerative.fit_predict(D)
    hlabels = agglomerative.labels_ 
    print (hlabels) 
    score = silhouette_score(D,hlabels)
    ARI=metrics.adjusted_rand_score(true_label, hlabels)
    print ("Silhouette Score", score)
    print ("ARI Score",ARI)

[1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 4 1 0 0 1 0 0 1
 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 3 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0
 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 3 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0
 1 0 0 1 0 0 1 0 0 1 0 0 2 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1
 0 0]
Silhouette Score 0.3424088551001327
ARI Score 0.551796444741071
